config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/new'
  # get 'bookmarks/create'
  # get 'bookmarks/show'
  # get 'bookmarks/delete'
  # get 'lists/index'
  # get 'lists/new'
  # get 'lists/create'
  # get 'lists/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[new create show delete]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :list, scope: :movie
end

# Un signet doit être lié à un film et une liste, et les associations [film, liste] doivent être uniques.
# Le commentaire associé à un signet ne peut pas avoir moins de 6 caractères.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save

    redirect_to list_path(@list)
  end

  def show
  end

  def delete
    @bookmark = bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  def show
    @list = List.find(params[:id])
    # @bookmarks = Bookmark.where("list_id = #{params[:id]}")
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/delete.html.erb
<h1>Bookmarks#delete</h1>
<p>Find me in app/views/bookmarks/delete.html.erb</p>

app/views/bookmarks/new.html.erb
<h1><strong>New bookmark</strong></h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

<div id="back">
    <%= link_to "Back to lists" , lists_path %> | <br>
</div>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<h1><strong>All your lists of movies (<%= List.count%>) </strong></h1>

<div id="lists">
  <ul>
    <% @lists.each do |list| %>
    <li>
      <p>
      <%= link_to list.name, list_path(list) %>
      </p>
    </li>
    <% end %>
  </ul>
</div>

<%= link_to "Create a new list", new_list_path %>

app/views/lists/new.html.erb
<h1><strong>New list</strong></h1>


<%= render "form", list: @list %>

  <br>

<p><%= link_to "Back to lists", lists_path %></p>

app/views/lists/show.html.erb
<h1><strong><%= @list.name %></strong></h1>

<div id="movies">
 <ul>
  <% @list.bookmarks.each do |bookmark| %>
  <%= bookmark.movie.title %>
  <%= bookmark.movie.overview %>
  <% end %>
</ul>
</div>


<%= link_to "Create a new bookmark", new_list_bookmark_path(@list, @bookmark) %> <br>
<p><%= link_to "Back to lists", lists_path %></p>